[package]
name = "ttl-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt", "sync", "time"]}

[dev-dependencies]
lazy_static = "1.4.0"
mockall = "0.11.4"