name: Checks

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.68.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@ce8f65846d7180d2ce63b1e74483d981800b9e22
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Build
        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@ce8f65846d7180d2ce63b1e74483d981800b9e22
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Test
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@ce8f65846d7180d2ce63b1e74483d981800b9e22
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy

      - name: Run Fmt Check
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@ce8f65846d7180d2ce63b1e74483d981800b9e22
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
